apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 753324040823.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 753324040823.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 173adabe
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
